"""Create Book model

Revision ID: c7b50f451bde
Revises: 
Create Date: 2026-10-03 17:52:37.114208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b50f451bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('bookId', sa.Integer(), nullable=False),
    sa.Column('bookTitle', sa.String(length=50), nullable=False),
    sa.Column('bookAuthor', sa.String(length=50), nullable=False),
    sa.Column('bookYear', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bookId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
